package seedu.classmate;
import seedu.classmate.commands.RemoveSpecialisationCommand;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;

/**
 * Unit tests for the {@code RemoveSpecialisationCommand} class.
 * Ensures that specialisations can be safely removed, handles case-insensitivity,
 * and verifies that proper exceptions are thrown for invalid or missing data.
 */
public class RemoveSpecialisationCommandTest {
    private static final String TEST_MODULES_FILE = "data/testModules.txt";
    private static final String TEST_SPECS_FILE = "data/testSpecs.txt";

    private Major major;
    private SpecialisationOverview specOverview;
    private Ui ui;
    private Storage storage;
    private UserProfile userProfile;

    /**
     * Sets up the testing environment before each test.
     * Initializes dummy curriculum data, a fake storage environment, and a clean user profile.
     */
    @BeforeEach
    public void setUp() {
        // Initialise dummy curriculum data
        major = new Major(new ArrayList<>());
        specOverview = new SpecialisationOverview(new HashMap<>());
        ui = new Ui();

        // Initialise test storage and empty profile
        storage = new Storage(TEST_MODULES_FILE, TEST_SPECS_FILE);
        userProfile = new UserProfile(new ArrayList<>(), new ArrayList<>());
    }

    /**
     * Creates a SpecialisationOverview with valid specialisation names for validation checks.
     */
    private SpecialisationOverview createValidSpecOverview() {
        HashMap<String, ArrayList<Module>> specMap = new HashMap<>();
        specMap.put("Robotics", new ArrayList<>());
        specMap.put("Internet of Things", new ArrayList<>());
        specMap.put("Space Technology", new ArrayList<>());
        specMap.put("Industry 4.0", new ArrayList<>());
        specMap.put("Advanced Electronics", new ArrayList<>());
        specMap.put("Others", new ArrayList<>());
        return new SpecialisationOverview(specMap);
    }

    /**
     * Cleans up the testing environment after each test.
     * Deletes the temporary text files generated by the Storage class to prevent data leaking between tests.
     */
    @AfterEach
    void cleanup() {
        new File(TEST_MODULES_FILE).delete();
        new File(TEST_SPECS_FILE).delete();
    }

    /**
     * Tests the successful removal of an existing specialisation using an exact string match.
     * Verifies that the specialisation list becomes empty after execution.
     *
     * @throws ClassMateException if an unexpected error occurs during profile modification.
     */
    @Test
    void execute_validSpecialisation_removesSuccessfully() throws ClassMateException {
        // Add a specialisation first
        userProfile.addSpecialisation("Robotics");
        assertEquals(1, userProfile.getUserSpecialisations().size());

        // Run the remove command
        RemoveSpecialisationCommand cmd = new RemoveSpecialisationCommand("Robotics", userProfile, storage);
        assertDoesNotThrow(() -> cmd.executeCommand(major, ui, createValidSpecOverview()));

        // Since there was only one spec, removing the spec should make list empty
        assertTrue(userProfile.getUserSpecialisations().isEmpty());
    }

    /**
     * Tests that the removal logic is case-insensitive.
     * Verifies that inputting a lowercase string will successfully remove a capitalized specialisation.
     *
     * @throws ClassMateException if an unexpected error occurs during profile modification.
     */
    @Test
    void execute_caseInsensitive_removesSuccessfully() throws ClassMateException {
        // Add specialisation with one capital letter
        userProfile.addSpecialisation("Robotics");

        // Try to remove with all lowercase
        RemoveSpecialisationCommand cmd = new RemoveSpecialisationCommand("robotics", userProfile, storage);
        assertDoesNotThrow(() -> cmd.executeCommand(major, ui, createValidSpecOverview()));

        // Specialisation should still be identified despite casing, and removed
        assertTrue(userProfile.getUserSpecialisations().isEmpty());
    }

    /**
     * Tests the behavior when attempting to remove a specialisation that the user has not selected.
     * Verifies that a {@code ClassMateException} is thrown and that existing valid specialisations are not deleted.
     *
     * @throws ClassMateException to setup the initial profile state.
     */
    @Test
    void execute_specialisationNotFound_throwsException() throws ClassMateException {
        // Add a specialisation first
        userProfile.addSpecialisation("Robotics");

        // Remove a different specialisation from the one added
        RemoveSpecialisationCommand cmd = new RemoveSpecialisationCommand("Space Technology", userProfile, storage);

        // Throw exception because spec to be removed isn't in user profile
        ClassMateException exception = assertThrows(ClassMateException.class,
                () -> cmd.executeCommand(major, ui, createValidSpecOverview()));

        assertEquals("Specialisation 'Space Technology' not found in your profile.", exception.getMessage());

        // Check that user's spec is not removed by accident
        assertEquals(1, userProfile.getUserSpecialisations().size());
        assertTrue(userProfile.getUserSpecialisations().contains("Robotics"));
    }

    /**
     * Tests the behavior when attempting to remove a specialisation from an empty profile.
     * Verifies that a {@code ClassMateException} is thrown with the appropriate warning message.
     */
    @Test
    void execute_emptyProfile_throwsException() {
        // Profile has no specialisations
        RemoveSpecialisationCommand cmd = new RemoveSpecialisationCommand("Robotics", userProfile, storage);

        // Then removing a spec when there's no spec should throw an exception
        ClassMateException exception = assertThrows(ClassMateException.class,
                () -> cmd.executeCommand(major, ui, createValidSpecOverview()));

        assertEquals("You haven't selected any specialisations to remove.", exception.getMessage());
    }

    /**
     * Tests the command's validation for empty or whitespace-only arguments.
     * Verifies that a {@code ClassMateException} is thrown instructing the user on proper formatting.
     */
    @Test
    void execute_emptyInput_throwsException() {
        RemoveSpecialisationCommand cmd = new RemoveSpecialisationCommand("", userProfile, storage);

        ClassMateException exception = assertThrows(ClassMateException.class,
                () -> cmd.executeCommand(major, ui, createValidSpecOverview()));

        assertEquals("Please provide a specialisation name. " +
                    "Format: removeSpecialisation <NAME>", exception.getMessage());
    }

    @Test
    void execute_invalidSpecialisation_throwsException() throws ClassMateException {
        userProfile.addSpecialisation("Robotics");

        RemoveSpecialisationCommand cmd = new RemoveSpecialisationCommand("Robotic", userProfile, storage);

        ClassMateException exception = assertThrows(ClassMateException.class,
                () -> cmd.executeCommand(major, ui, createValidSpecOverview()));

        assertEquals("Invalid specialisation name: Robotic", exception.getMessage());
        assertEquals(1, userProfile.getUserSpecialisations().size());
        assertTrue(userProfile.getUserSpecialisations().contains("Robotics"));
    }

}
